### ISSUE TITLE
非常感谢作者提供的数据集！在此附上国内各网盘的下载链接

### ISSUE THREAD

**Issue by Mekako** [Liudd-BJUT/WT-planetary-gearbox-datasets#1]
github的下载速度实在感人，所以我帮忙上传到百度网盘上了，方便国内的同学们下载！
链接：https://pan.baidu.com/s/1u_JoKA94QZ9i63OYgqj9yg?pwd=6666 
提取码：6666
链接长期有效，如果作者觉得不合适的话请联系我删除！
再次感谢！

**Comment by liguge** [comment]
那我提供一个阿里云盘的下载链接，这个基本不限速。
WT-planetary-gearbox-dataset-master
https://www.aliyundrive.com/s/4RCfcNqc4F4
提取码: 5lx4
点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

**Comment by liguge** [comment]
这里分享一个阿里云盘的下载链接，方便不同的人下载：
WT-planetary-gearbox-dataset
https://www.aliyundrive.com/s/sUbkpTcEdnR
点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

**Comment by Liudd-BJUT** [comment]
感谢

2023-10-26 10:40:46"Chao He" ***@***.***>写道：

这里分享一个阿里云盘的下载链接，方便不同的人下载：
WT-planetary-gearbox-dataset
https://www.aliyundrive.com/s/sUbkpTcEdnR
点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

**Comment by liguge** [comment]
> 感谢 2023-10-26 10:40:46"Chao He" ***@***.***>写道： 这里分享一个阿里云盘的下载链接，方便不同的人下载： WT-planetary-gearbox-dataset https://www.aliyundrive.com/s/sUbkpTcEdnR 点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

抱歉，没想到阿里云不允许分享，链接失效了。

**Comment by Liudd-BJUT** [comment]
嗯嗯

2023-10-29 09:41:59 "Chao He" ***@***.***> 写道：

感谢 2023-10-26 10:40:46"Chao He" @.>写道： 这里分享一个阿里云盘的下载链接，方便不同的人下载： WT-planetary-gearbox-dataset https://www.aliyundrive.com/s/sUbkpTcEdnR 点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>

抱歉，没想到阿里云不允许分享，链接失效了。

**Comment by xiaoxiaoqin0017** [comment]
数据集的变量是哪些啊？

**Comment by Mekako** [comment]
> 数据集的变量是哪些啊？

在作者论文实验部分有提到

**Comment by eureka124** [comment]
无法使用MATLAB
![image](https://github.com/user-attachments/assets/392bb2de-09b7-4a6e-b10c-5caad313dab8)
或者python `scipy.io.loadmat()`方法打开，
```
Traceback (most recent call last):
  File "C:\Users\1806476094\anaconda3\envs\DL\lib\site-packages\IPython\core\interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-59629290b057>", line 1, in <module>
    file=sio.loadmat(path)
  File "C:\Users\1806476094\anaconda3\envs\DL\lib\site-packages\scipy\io\matlab\_mio.py", line 226, in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
  File "C:\Users\1806476094\anaconda3\envs\DL\lib\site-packages\scipy\io\matlab\_mio.py", line 74, in mat_reader_factory
    mjv, mnv = _get_matfile_version(byte_stream)
  File "C:\Users\1806476094\anaconda3\envs\DL\lib\site-packages\scipy\io\matlab\_miobase.py", line 249, in _get_matfile_version
    raise ValueError('Unknown mat file type, version {}, {}'.format(*ret))
ValueError: Unknown mat file type, version 52, 55
```   

记事本打开后
![image](https://github.com/user-attachments/assets/8af6a317-cc30-4806-aae6-a9556ba20961)
文件大小也存疑，
![image](https://github.com/user-attachments/assets/6d7a732b-c7db-4ba7-bb02-90194fdfdc75)
使用Download ZIP 方式下载

**Comment by Mekako** [comment]
> 无法使用MATLAB ![image](https://private-user-images.githubusercontent.com/117238009/380157221-392bb2de-09b7-4a6e-b10c-5caad313dab8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MTI3MTYsIm5iZiI6MTcyOTkxMjQxNiwicGF0aCI6Ii8xMTcyMzgwMDkvMzgwMTU3MjIxLTM5MmJiMmRlLTA5YjctNGE2ZS1iMTBjLTVjYWFkMzEzZGFiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQwMzEzMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04N2NjZTU1NGFhMGYyYWU0NTVmMzUzMTk3MzcyNDc1NmMwMTU3Y2JlZWIzNWY2NzY5ZjFjYTc3MmJlZTdkYzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mHtsKgfYA9xUOnr-s6bBgmv-QMxJIAjapMr616oIEcs) 或者python `scipy.io.loadmat()`方法打开，
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\1806476094\anaconda3\envs\DL\lib\site-packages\IPython\core\interactiveshell.py", line 3505, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-4-59629290b057>", line 1, in <module>
>     file=sio.loadmat(path)
>   File "C:\Users\1806476094\anaconda3\envs\DL\lib\site-packages\scipy\io\matlab\_mio.py", line 226, in loadmat
>     MR, _ = mat_reader_factory(f, **kwargs)
>   File "C:\Users\1806476094\anaconda3\envs\DL\lib\site-packages\scipy\io\matlab\_mio.py", line 74, in mat_reader_factory
>     mjv, mnv = _get_matfile_version(byte_stream)
>   File "C:\Users\1806476094\anaconda3\envs\DL\lib\site-packages\scipy\io\matlab\_miobase.py", line 249, in _get_matfile_version
>     raise ValueError('Unknown mat file type, version {}, {}'.format(*ret))
> ValueError: Unknown mat file type, version 52, 55
> ```
> 
> 记事本打开后 ![image](https://private-user-images.githubusercontent.com/117238009/380155941-8af6a317-cc30-4806-aae6-a9556ba20961.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MTI3MTYsIm5iZiI6MTcyOTkxMjQxNiwicGF0aCI6Ii8xMTcyMzgwMDkvMzgwMTU1OTQxLThhZjZhMzE3LWNjMzAtNDgwNi1hYWU2LWE5NTU2YmEyMDk2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQwMzEzMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2Y0YWZmOWFiOWE0ODU1YzMxYzQ3M2FlOWRmYWYyNWMzNGY5YTFlZWM1ZTQ4NzY2MDhmNDFmZDcyMjQyOGI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Wc5uvHC0oOk6ihcZJtv9FCK8wMuz3waI-lNphCcwpwg) 文件大小也存疑， ![image](https://private-user-images.githubusercontent.com/117238009/380156606-6d7a732b-c7db-4ba7-bb02-90194fdfdc75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MTI3MTYsIm5iZiI6MTcyOTkxMjQxNiwicGF0aCI6Ii8xMTcyMzgwMDkvMzgwMTU2NjA2LTZkN2E3MzJiLWM3ZGItNGJhNy1iYjAyLTkwMTk0ZmRmZGM3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQwMzEzMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjZjODc1OTg3Y2ZiODcwZmNlYjk0YjI1YTZjNzUxNWVjOTgxMWQ4MDU1ZmFkYTQ4ZjgwYzczYjk2YzQ5NmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.n5K1KXKucjQUhoXhbBwYLX0j1W-raHJDiMAtEH9_zHc) 使用Download ZIP 方式下载

这是因为github中的大型文件并不能直接以这种方式下载，需要使用Git LFS:Git Large File Storage(LFS)进行拉取，速度比较慢，所以我当时上传到百度网盘供大家下载，没想到被和谐了。具体下载方式搜索Git LFS的使用就行

**Comment by Struggle-best** [comment]
夸克网盘链接：
链接：https://pan.quark.cn/s/920cd614192a?pwd=LEsJ
提取码：LEsJ
